name: app_tinh_tien
description: Ung dung tinh tien quan an
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^6.0.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^11.6.9
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
